version: "3.6"

services:

  api:
    image: asdfry/infer-vision:20231119
    volumes:
      - /home/jsh/volume:/root/mnt:ro
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 1047:8000
    environment:
      - DTYPE=fp16
      - MODEL_NAME=resnet-50
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
